"""Bounded PDF-corpus discovery and ingestion application composition."""

from .composition import compose_pdf_corpus_ingestion_plan
from .document_package import (
    DOCUMENT_PACKAGE_CONTRACT_ID,
    DOCUMENT_PACKAGE_MANIFEST,
    DOCUMENT_PACKAGE_SCHEMA_VERSION,
    DeterministicDocumentPackage,
    DocumentPackageArtifact,
    DocumentPackageError,
    DocumentPackagePublicationAction,
    DocumentPackagePublicationError,
    build_deterministic_document_package,
    publish_deterministic_document_package,
)
from .equation_review import (
    EQUATION_REVIEW_CONTRACT_ID,
    EQUATION_REVIEW_SCHEMA_VERSION,
    AssistedEquationAttempt,
    EquationReviewConcurrencyError,
    EquationReviewDisposition,
    EquationReviewError,
    EquationReviewEvidenceBinding,
    EquationReviewEvidenceMismatch,
    EquationReviewPublicationAction,
    EquationReviewPublicationError,
    EquationReviewStaleRevision,
    HumanEquationRevision,
    HumanEquationRevisionAppendResult,
    HumanEquationRevisionRequest,
    append_human_equation_revision,
    load_latest_human_equation_revision,
    publish_assisted_equation_attempt,
)
from .multimodal import PdfCorpusMultimodalPolicy
from .plan import (
    MAX_APPLICATION_PDF_BYTES,
    MAX_APPLICATION_PDF_PAGES,
    MAX_TRANCHE_ITEMS,
    PdfCorpusIngestionPlan,
    PdfCorpusItemDisposition,
    PdfCorpusLocation,
    PdfCorpusPlanError,
    PdfCorpusPlanItem,
)

__all__ = [
    "DOCUMENT_PACKAGE_CONTRACT_ID",
    "DOCUMENT_PACKAGE_MANIFEST",
    "DOCUMENT_PACKAGE_SCHEMA_VERSION",
    "EQUATION_REVIEW_CONTRACT_ID",
    "EQUATION_REVIEW_SCHEMA_VERSION",
    "MAX_APPLICATION_PDF_BYTES",
    "MAX_APPLICATION_PDF_PAGES",
    "MAX_TRANCHE_ITEMS",
    "AssistedEquationAttempt",
    "DeterministicDocumentPackage",
    "DocumentPackageArtifact",
    "DocumentPackageError",
    "DocumentPackagePublicationAction",
    "DocumentPackagePublicationError",
    "EquationReviewConcurrencyError",
    "EquationReviewDisposition",
    "EquationReviewError",
    "EquationReviewEvidenceBinding",
    "EquationReviewEvidenceMismatch",
    "EquationReviewPublicationAction",
    "EquationReviewPublicationError",
    "EquationReviewStaleRevision",
    "HumanEquationRevision",
    "HumanEquationRevisionAppendResult",
    "HumanEquationRevisionRequest",
    "PdfCorpusIngestionPlan",
    "PdfCorpusItemDisposition",
    "PdfCorpusLocation",
    "PdfCorpusMultimodalPolicy",
    "PdfCorpusPlanError",
    "PdfCorpusPlanItem",
    "append_human_equation_revision",
    "build_deterministic_document_package",
    "compose_pdf_corpus_ingestion_plan",
    "load_latest_human_equation_revision",
    "publish_assisted_equation_attempt",
    "publish_deterministic_document_package",
]
